### ISSUE TITLE
Multiple Packages found with the same name "project_vs"

### ISSUE THREAD

**Issue by aarontan-git** [PamirGhimire/visualServoing_ROSProject#2]
Hello,

When I git cloned your repo in to catkin_ws, I also receive the following error message upon catkin_make:

Base path: /home/grasp/catkin_ws
Source space: /home/grasp/catkin_ws/src
Build space: /home/grasp/catkin_ws/build
Devel space: /home/grasp/catkin_ws/devel
Install space: /home/grasp/catkin_ws/install
Multiple packages found with the same name "project_vs":
- visualServoing_ROSProject/IBVS_PointsBased
- visualServoing_ROSProject/PoseBased

Please help.

**Comment by PamirGhimire** [comment]
hi, try cloning just one folder into your ws/src, for example, the
posebased folder, see if you can catkin_make

**Comment by AnukritiSinghh** [comment]
Hi, I faced the similar issue and hence cloned only pointbased, but got the following error (screenshot). Can you please help me?
![image](https://user-images.githubusercontent.com/28527591/147049730-ced16e63-7d11-4bb6-a0cb-197d5caa7c04.png)
